apiVersion: v1
kind: Namespace
metadata:
  name: cicd
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cicd-nginx
  namespace: cicd
  labels:
    app: nginx
    project: cicd
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: ponetagon/cicd-nginx:v1
        ports:
        - containerPort: 80
#      imagePullSecrets:
#      - name: registry
---
apiVersion: v1
kind: Service
metadata:
  name: cicd-nginx
  namespace: cicd
  labels:
    app: nginx
    project: cicd
spec:
  type: NodePort
  ports:
  - protocol: TCP
    port: 80
